kind: pipeline
name: deploy

steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule update --init --recursive
  - name: build-site
    image: garykim/hugo:0-extended
    pull: always
    commands:
      - make prod
  - name: deploy-site
    image: garykim/rclone
    pull: always
    environment:
      RCLONE_CONFIG_PASS:
        from_secret: rclone_config_pass
    commands:
      - make deploy
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/website

trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: secret
name: rclone_config_pass
data: t/tqPP90eLpZaJn1pBvybGjre10oV0n5L8WEkDAjiKXGDylP2+92dUr2M9PBLgpq
